version: 2.1

jobs: 
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout 
      - run: echo "hello from build job..."
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout 
      - run: echo "hello from deploy job..."
  deployment-markers: 
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "hello from deployment-marker job..."

workflows:
  everything:
    jobs: 
      - build
      - deploy
      - deployment-markers

