version: 2.1

jobs:
  deploy-production:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Send deployment markers
          command: |
            echo "sending deployment markers..."




