version: 2.1 

jobs:
  # build: 
  #   docker:
  #     - image: circleci/node:latest
  #   steps:
  #     - checkout 
  #     - run: 
  #         name: Building project
  #         command: |
  #           echo "building project..."            
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 
      - run: 
          name: Deployment markers for new relic
          command: |
            set 
            echo "CIRCLE REPOSITORY: $CIRCLE_REPOSITORY_URL"
            echo "CIRCLE BRANCH: $CIRCLE_BRANCH"
            echo "CIRCLE TAG: $CIRCLE_TAG"
            echo "CIRCLE SHA1: $CIRCLE_SHA1"            
            echo "Sending deployment marker to newrelic..."
            curl  -X POST "https://api.newrelic.com/v2/applications/${NR_APP_ID}/deployments.json" \
                  -H "X-Api-Key: ${NR_API_KEY}" \
                  -H "Content-Type: application/json" \
                  -d \
                  '{
                    "deployment":{
                      "revision": "git-commit: ${CIRCLE_SHA1}",
                      "user": "phaberern@redventures.com",
                      "timestamp": ""
                    }
                  }' 
      - run:
          name: Emit event to event bus
          command: |
            sudo apt-get install awscli 
            aws configure set aws_access_key $AWS_ACCESS_KEY_PRODUCTION
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_PRODUCTION
            aws configure set region us-east-1
                        

# workflows:
#   build-deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: /.*/
#       - deploy-production:
#           requires:
#             - build 
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^V.*/


  

    


