version: 2.1

jobs: 
  build:
    steps:
      - checkout 
      - run: echo "hello from build job..."
  deploy:
    steps:
      - checkout 
      - run: echo "hello from deploy job..."
  deployment-markers: 
    steps:
      - checkout
      - run: echo "hello from deployment-marker job..."

workflows:
  deploy-staging:
    jobs:
      - build
      - deploy
  deploy-production:
    jobs:
      - build
      - deploy
      - deployment-markers