version: 2.1 

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 
      - run: 
          name: Printing out environment variables
          command: |
            echo "CIRCLE REPOSITORY: $CIRCLE_REPOSITORY_URL"
            echo "CIRCLE BRANCH: $CIRCLE_BRANCH"
            echo "CIRCLE TAG: $CIRCLE_TAG"
            echo "GIT COMMIT: $CIRCLE_SHA1"

  

    


