version: 2.1

jobs:     
  deploy-production: 
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
        name: Sending deployment markers to event bridge
        command: |
          echo "sending deployment markers to event bridge..."


