version: 2.1 

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 
      - run: 
          name: Printing out environment variables
          command: |
            echo "CIRCLE REPOSITORY: $CIRCLE_REPOSITORY_URL"
            echo "CIRCLE BRANCH: $CIRCLE_BRANCH"
            echo "CIRCLE TAG: $CIRCLE_TAG"
            echo "GIT COMMIT: $CIRCLE_SHA1"
            echo "Sending deployment marker to newrelic..."
            curl  -X POST "https://api.newrelic.com/v2/applications/437777006/deployments.json" \
                  -H "X-Api-Key: NRAA-89ad215d4a8a8986643722d8aeb" \
                  -H "Content-Type: application/json" \
                  -d \
                  '{
                    "deployment":{
                      "revision": "test-revision-from-circle",
                      "user": "phaberern@redventures.com",
                      "timestamp": ""
                    }
                  }'          

  

    


